apiVersion: v1
kind: Service

metadata:
  name: simple-api-svc
  namespace: api
spec:
  selector:
    app: simple-api
  
  ports:
  - protocol: TCP
    port: 8080 
    targetPort: http
  #   nodePort: 31080
  # type: NodePort
  


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-api
  namespace: api
  labels:
    app: simple-api
    
   
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-api
  template:
    metadata:
      labels:
        app: simple-api
        
    spec:
      containers:
      - name: simple-api
        image: saturn203/simple-api
        # imagePullPolicy: Never
        ports:
        - name: http
          containerPort: 8080
         
        # env:
        # - name: MYSQL_USERNAME
        #   valueFrom:
        #     secretKeyRef:
        #       name: mysqldb-secret
        #       key: username
        # - name: MYSQL_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: mysqldb-secret
        #       key: password
        # readinessProbe:
        #   httpGet:
        #     path: /sys/healthz
        #     port: http
        #   initialDelaySeconds: 5
        #   periodSeconds: 2
      # nodeSelector:
      #   nodegroup-type: backend

        # resources: 
        #   limits: 
        #     cpu: 250m 
        #     memory: 32Mi


    
